#!/user/bin/env bash
profile=$AUTORANDR_CURRENT_PROFILE
dir=$AUTORANDR_PROFILE_FOLDER

#(sleep 1 && xmonad --restart)&
case "$profile" in
    rv-laptop)
        sed -i 's/size: .*$/size: 10/' ~/.config/alacritty/alacritty.yml
        dconf write /org/gnome/desktop/interface/text-scaling-factor 1.0
        ;;
    rv-dual)
        sed -i 's/size: .*$/size: 12/' ~/.config/alacritty/alacritty.yml
        dconf write /org/gnome/desktop/interface/text-scaling-factor 1.2
        ;;
    nv-laptop)
        sed -i 's/size: .*$/size: 10/' ~/.config/alacritty/alacritty.yml
        dconf write /org/gnome/desktop/interface/text-scaling-factor 1.0
        #nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
        ;;
    nv-dual)
        sed -i 's/size: .*$/size: 12/' ~/.config/alacritty/alacritty.yml
        dconf write /org/gnome/desktop/interface/text-scaling-factor 1.2
        #nvidia-settings --assign CurrentMetaMode="DP-1: nvidia-auto-select +1920+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DP-2: nvidia-auto-select +0+1080 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
        ;;
esac
